# Generated by Django 2.2.7 on 2020-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysketchpad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
